### ISSUE TITLE
Can't install the archive: "Installation failed: invalid archive file"

### ISSUE THREAD

**Issue by sotojuan** [riverrun/phauxth_installer#1]
Elixir 1.5.2 with OTP 20.

Running `mix archive.install https://github.com/riverrun/phauxth_installer/blob/master/archives/phauxth_new.ez` results in the above error message. Any clues?

Thanks for any help and your work!

**Comment by riverrun** [comment]
I've just updated the archive. If that fails, try compiling it locally and installing it that way (the instructions are in the README).

**Comment by sotojuan** [comment]
I was able to install it locally after making this issue and installing from GitHub is working. Thanks.

**Comment by riverrun** [comment]
Great!

**Comment by dsignr** [comment]
This is an issue again, unfortunately :(
