### ISSUE TITLE
Dependencies aren't getting added with Phoenix 1.4

### ISSUE THREAD

**Issue by BryanJBryce** [riverrun/phauxth_installer#10]
Running the installer with Phoenix 1.4:

At the end of installation the installer says:

>bcrypt_elixir has been added to the mix.exs file as a dependency.
If you want to use argon2_elixir or pbkdf2_elixir instead, edit
the mix.exs file, replacing bcrypt_elixir with the hashing library
you want to use.

>bamboo has been added to the mix.exs file as a dependency.
If you want to use a different library to email users, edit
the mix.exs file.

Checking the mix.exs file shows this for the dependencies:

  ```
defp deps do
    [
      {:phoenix, "~> 1.4.0-rc"},
      {:phoenix_pubsub, "~> 1.1"},
      {:phoenix_ecto, "~> 3.5"},
      {:ecto, "~> 3.0-rc", override: true},
      {:ecto_sql, "~> 3.0-rc", override: true},
      {:postgrex, ">= 0.0.0-rc"},
      {:phoenix_html, "~> 2.11"},
      {:phoenix_live_reload, "~> 1.2-rc", only: :dev},
      {:gettext, "~> 0.11"},
      {:jason, "~> 1.0"},
      {:plug_cowboy, "~> 2.0"}
    ]
  end
```

**Comment by riverrun** [comment]
I know what's happening here. I will look at this today.

**Comment by riverrun** [comment]
Fixed
