### ISSUE TITLE
function Phauxth.Token.sign/2 is undefined or private after installing on fresh Phoenix 1.4.0

### ISSUE THREAD

**Issue by ghost** [riverrun/phauxth_installer#12]
When trying to create a new user on a fresh install I get the following. 

```
Request: POST /users
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Phauxth.Token.sign/2 is undefined or private
        (phauxth) Phauxth.Token.sign(%Plug.Conn{adapter: {Plug.Cowboy.Conn, :...}, assigns: %{current_user: nil},
```

phoenix Version: https://github.com/phoenixframework/phoenix/commit/12785c3809b9cd35261e0093be531ab737b88b7f

phauxth Version:
https://github.com/riverrun/phauxth/commit/75cd7e176ccfccca1705b0e2e1a26f3dcd7650b8

I suspect the generator just needs to be updated. I plan to do it, just wanted this ticket as reference.
Unless you think this is a false positive in which case feel free to close else I will if I find that to the case.

**Comment by ghost** [comment]
Ah so my bad, I didn't realize so much of the example app has changed vs what has been done in the installer. It looks like to me you guys are building out the example app out first to get the template that will be used in the installer.  Any how gonna close this as this is a broader task. What kind of process did you have in mind for when you wanted to update the installer? I'm happy to help with that otherwise I'd guess the remaining work is still in the example app?

**Comment by riverrun** [comment]
A basic version of the installer for 2.0.0 should be ready in a couple of days time. I will keep eveyone informed on the Gitter channel.
