### ISSUE TITLE
** (Mix) Installation failed: invalid archive file

### ISSUE THREAD

**Issue by happysalada** [riverrun/phauxth_installer#2]
running
```
Erlang/OTP 20 [erts-9.1.2] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.5.2
```
with phoenix 1.3
trying to do the install command
`mix archive.install https://github.com/riverrun/phauxth_installer/blob/master/archives/phauxth_new.ez`
I get the following error
`** (Mix) Installation failed: invalid archive file`

did I forget to do something ?

**Comment by riverrun** [comment]
Could you try installing it locally?

First clone the repository and then run the following commands:

```elixir
cd phauxth_new
MIX_ENV=prod mix build
cd ../archives
mix archive.install phauxth_new.ez
```

**Comment by riverrun** [comment]
The link is wrong. It should be https://github.com/riverrun/phauxth_installer/raw/master/archives/phauxth_new.ez

**Comment by riverrun** [comment]
I have just changed the link in the documentation and the wiki.

Let me know if you have any further problems.

**Comment by happysalada** [comment]
Thanks for the super quick feedback, I'll try again tomorrow and update if there is any problem
