### ISSUE TITLE
Installer generated password validation allows empty password

### ISSUE THREAD

**Issue by zerosym** [riverrun/phauxth_installer#6]
Specifically -- this line does not include the password field in the required validator list.
https://github.com/riverrun/phauxth_installer/blob/a37ae3fb73bee6178dd66a5d193bd8dc6360a204/phauxth_new/templates/user.ex#L27

The validate password method skips over its check since the password field is not present in the changeset when empty.
https://github.com/riverrun/phauxth_installer/blob/a37ae3fb73bee6178dd66a5d193bd8dc6360a204/phauxth_new/templates/user.ex#L44

**Comment by riverrun** [comment]
Well spotted :)

Now fixed in the latest update.
